services:
  monorepo_dev:
    environment:
      - NODE_ENV

    container_name: nestjs-remix-monorepo-dev
    build:
      context: .
      dockerfile: Dockerfile
    # image: varkoff/nestjs-remix-monorepo:dev
    restart: always
    ports:
      - 3000:3000
