services:
  monorepo_dev:
    environment:
      - REDIS_URL=redis://redis_dev:6379
      - NODE_ENV=development
      - DATABASE_URL

    container_name: nestjs-remix-monorepo-dev
    build:
      context: .
      dockerfile: Dockerfile
    # image: varkoff/nestjs-remix-monorepo:dev
    restart: always
    ports:
      - 3000:3000
  redis_dev:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: ["redis-server"] 
    # --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - ./cache:/data
      # - /dev/volumes/nestjs-remix/dev/sessions/:/data
